# Generated by Django 2.0 on 2022-11-23 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0003_auto_20180605_0842'),
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='census',
            name='voting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
        ),
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('name', 'voting_id')},
        ),
    ]
