# Generated by Django 2.0 on 2022-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCensus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census', models.FileField(upload_to='csv')),
            ],
        ),
    ]
