# Generated by Django 2.0 on 2022-11-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_auto_20221119_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='census',
            old_name='voters',
            new_name='voter_id',
        ),
    ]
