# Generated by Django 2.0 on 2022-11-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_auto_20221119_2017'),
        ('census', '0002_auto_20221123_1333'),
        ('census', '0002_exportcensus'),
    ]

    operations = [
    ]
