# Generated by Django 2.0 on 2022-11-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='yesorno',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(blank=True, null=True),
        ),
    ]
