# Generated by Django 2.0 on 2022-11-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20221130_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='boolean',
        ),
    ]
