# Generated by Django 2.0 on 2022-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_questionoption_yesorno'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField()),
            ],
        ),
    ]
