# Generated by Django 2.0 on 2022-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_questionbool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBool',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='boolean',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(),
        ),
    ]
