# Generated by Django 2.0 on 2022-11-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20221130_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.Question'),
        ),
    ]
