# Generated by Django 2.0 on 2022-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20221130_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='boolean',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='no',
            field=models.NullBooleanField(verbose_name='yes'),
        ),
    ]
