# Generated by Django 2.0 on 2022-11-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20221130_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='no',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='boolean',
            field=models.NullBooleanField(verbose_name='Sí o No'),
        ),
    ]
