# Generated by Django 2.0 on 2022-12-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20221130_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='desc',
        ),
    ]
