# Generated by Django 2.0 on 2022-11-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20221130_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='sino',
            new_name='boolean',
        ),
    ]
