# Generated by Django 2.0 on 2022-12-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_remove_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='desc',
            field=models.TextField(default=' '),
        ),
    ]
